ALTER TABLE move_profiles
  ADD COLUMN IF NOT EXISTS timeline_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS work_study_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS budget_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS family_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS urgency_level TEXT,
  ADD COLUMN IF NOT EXISTS must_arrive_before TEXT,
  ADD COLUMN IF NOT EXISTS flexible_dates BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_job_offer BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_school_admission BOOLEAN,
  ADD COLUMN IF NOT EXISTS employer_or_school_name TEXT,
  ADD COLUMN IF NOT EXISTS expected_monthly_budget_range TEXT,
  ADD COLUMN IF NOT EXISTS emergency_fund_range TEXT,
  ADD COLUMN IF NOT EXISTS dependents_count INTEGER;
